application:
  name: Example
commandler:
  integration:
    - "org.elypia.commandler.console.ConsoleIntegration"
  dispatcher:
    - "org.elypia.commandler.dispatchers.StandardDispatcher"
  controller:
    - type: "org.elypia.example.UtilityController"
      name: "Utilities"
      description: "Random utilities to add some quick generic functionality."
      property:
        - name: "org.elypia.commandler.dispatchers.StandardDispatcher.aliases"
          value: "utils"
      command:
        - method: "ping"
          name: "ping!"
          description: "Check if the application is still responsive!"
          static: "true"
          property:
            - name: "org.elypia.commandler.dispatchers.StandardDispatcher.aliases"
              value: "ping"
        - method: "sum"
          name: "Sum"
          description: "Add up a bunch of integer numbers."
          static: "true"
          property:
            - name: "org.elypia.commandler.dispatchers.StandardDispatcher.aliases"
              value: "sum"
          param:
            - name: numbers
              description: All the numbers I should sum together!
  messenger:
    - type: "org.elypia.commandler.console.messengers.MiscMessenger"
      provides: "java.lang.String"
      compatible:
        - "java.lang.Boolean"
        - "java.lang.CharSequence"
        - "java.lang.Character"
        - "java.net.URL"
    - type: "org.elypia.commandler.console.messengers.NumberMessenger"
      provides: "java.lang.String"
      compatible:
        - "java.lang.Number"
        - "java.lang.Double"
        - "java.lang.Float"
        - "java.lang.Long"
        - "java.lang.Integer"
        - "java.lang.Short"
        - "java.lang.Byte"
